// Budget Pathway Data — Sri Lanka focused
// Each career has a traditional pathway and multiple affordable alternatives

export const budgetPathways = {
  "software-engineer": {
    title: "Software Engineer",
    description: "Design, develop, and maintain software systems and applications across a wide range of industries.",
    requiredSkills: ["Programming", "Data Structures", "Algorithms", "Version Control", "APIs", "Databases", "Software Design"],
    avgStartingSalary: 85000,
    traditional: {
      label: "University Degree",
      type: "BSc Computer Science / IT",
      institution: "SLIIT / UoM / NSBM",
      duration: "3–4 years",
      cost: 1200000,
      costBreakdown: { tuition: 800000, living: 280000, materials: 60000, exams: 60000 },
      outcomes: ["Internationally recognised", "Strong foundation", "Research opportunities", "Higher entry salary"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Software Engineering",
        institution: "ESOFT / IJSE / NIBM",
        duration: "1–2 years",
        cost: 180000,
        costBreakdown: { tuition: 120000, living: 40000, materials: 12000, exams: 8000 },
        outcomes: ["Industry-ready skills", "Practical projects", "Job-focused curriculum"],
        skillsGained: ["Full Stack Dev", "OOP", "Version Control", "Databases"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "AWS + Meta + freeCodeCamp",
        institution: "Online (Coursera / Udemy)",
        duration: "6–12 months",
        cost: 35000,
        costBreakdown: { tuition: 25000, living: 0, materials: 5000, exams: 5000 },
        outcomes: ["Globally recognised certs", "Self-paced", "Portfolio driven", "Freelance-ready"],
        skillsGained: ["JavaScript", "React", "Node.js", "AWS Basics"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Bootcamp",
        type: "Intensive Coding Bootcamp",
        institution: "IJSE / Code Camps LK",
        duration: "3–6 months",
        cost: 75000,
        costBreakdown: { tuition: 60000, living: 0, materials: 10000, exams: 5000 },
        outcomes: ["Rapid skill acquisition", "Career support", "Real-world projects"],
        skillsGained: ["HTML/CSS/JS", "React", "REST APIs", "Git"],
        badge: "Fast Track",
        badgeColor: "bg-orange-100 text-orange-700",
        highlight: false,
      },
    ],
  },
  "data-analyst": {
    title: "Data Analyst",
    description: "Interpret complex data sets to help organisations make informed decisions using statistical techniques and tools.",
    requiredSkills: ["SQL", "Python", "Excel", "Statistics", "Data Visualization", "Power BI", "Tableau"],
    avgStartingSalary: 75000,
    traditional: {
      label: "University Degree",
      type: "BSc Data Science / Statistics",
      institution: "UoM / NSBM / SLIIT",
      duration: "3–4 years",
      cost: 1100000,
      costBreakdown: { tuition: 750000, living: 260000, materials: 50000, exams: 40000 },
      outcomes: ["Deep statistical foundation", "Research-ready", "Industry credibility"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Data Analytics",
        institution: "NIBM / ESOFT",
        duration: "1 year",
        cost: 120000,
        costBreakdown: { tuition: 80000, living: 24000, materials: 10000, exams: 6000 },
        outcomes: ["SQL & BI tools", "Practical datasets", "Industry projects"],
        skillsGained: ["SQL", "Power BI", "Excel Advanced", "Python Basics"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "Google Data Analytics Certificate",
        institution: "Coursera (Online)",
        duration: "6 months",
        cost: 18000,
        costBreakdown: { tuition: 15000, living: 0, materials: 2000, exams: 1000 },
        outcomes: ["Google-backed certificate", "Hands-on projects", "Job-ready portfolio"],
        skillsGained: ["R", "Tableau", "SQL", "Spreadsheets"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Self-Learning Path",
        type: "Kaggle + freeCodeCamp + YouTube",
        institution: "Online (Free)",
        duration: "4–8 months",
        cost: 5000,
        costBreakdown: { tuition: 0, living: 0, materials: 3000, exams: 2000 },
        outcomes: ["Zero cost", "Community driven", "Real Kaggle competitions"],
        skillsGained: ["Python", "Pandas", "Matplotlib", "SQL"],
        badge: "Free Path",
        badgeColor: "bg-teal-100 text-teal-700",
        highlight: false,
      },
    ],
  },
  "ui-ux-designer": {
    title: "UI/UX Designer",
    description: "Create intuitive digital experiences through user research, wireframing, prototyping, and visual design.",
    requiredSkills: ["Figma", "Wireframing", "Prototyping", "User Research", "Visual Design", "Adobe XD"],
    avgStartingSalary: 65000,
    traditional: {
      label: "University Degree",
      type: "BSc Design / HCI",
      institution: "IIT / SLIIT",
      duration: "3–4 years",
      cost: 1400000,
      costBreakdown: { tuition: 1000000, living: 280000, materials: 80000, exams: 40000 },
      outcomes: ["Comprehensive design theory", "HCI expertise", "Portfolio of projects"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in UI/UX Design",
        institution: "ESOFT / IIT",
        duration: "1 year",
        cost: 150000,
        costBreakdown: { tuition: 100000, living: 30000, materials: 15000, exams: 5000 },
        outcomes: ["Figma & Adobe mastery", "Real client projects", "Portfolio building"],
        skillsGained: ["Figma", "Wireframing", "Prototyping", "Visual Design"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "Google UX Design Certificate",
        institution: "Coursera (Online)",
        duration: "6 months",
        cost: 20000,
        costBreakdown: { tuition: 16000, living: 0, materials: 3000, exams: 1000 },
        outcomes: ["Google-backed", "7-course program", "3 portfolio projects"],
        skillsGained: ["UX Research", "Prototyping", "Figma", "User Testing"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Short Course",
        type: "UI/UX Crash Course",
        institution: "Interaction Design Foundation",
        duration: "3 months",
        cost: 8000,
        costBreakdown: { tuition: 6000, living: 0, materials: 2000, exams: 0 },
        outcomes: ["Quick entry", "Industry frameworks", "Community access"],
        skillsGained: ["Design Thinking", "User Research", "Usability Testing"],
        badge: "Quick Start",
        badgeColor: "bg-amber-100 text-amber-700",
        highlight: false,
      },
    ],
  },
  "cybersecurity-specialist": {
    title: "Cybersecurity Specialist",
    description: "Protect systems, networks and data from digital threats, vulnerabilities and cyberattacks.",
    requiredSkills: ["Networking", "Linux", "Ethical Hacking", "Firewalls", "Risk Assessment", "Cryptography", "SIEM"],
    avgStartingSalary: 95000,
    traditional: {
      label: "University Degree",
      type: "BSc Cybersecurity / Computer Science",
      institution: "UCSC / SLIIT",
      duration: "3–4 years",
      cost: 1250000,
      costBreakdown: { tuition: 850000, living: 280000, materials: 70000, exams: 50000 },
      outcomes: ["Deep technical foundation", "Research opportunities", "High earning potential"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Cybersecurity",
        institution: "SLIIT / NIBM",
        duration: "1–2 years",
        cost: 200000,
        costBreakdown: { tuition: 140000, living: 40000, materials: 12000, exams: 8000 },
        outcomes: ["Practical lab training", "Networking fundamentals", "Entry-level ready"],
        skillsGained: ["Networking", "Linux", "Firewalls", "Risk Assessment"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "CompTIA Security+ / CEH",
        institution: "Online / ACBT Sri Lanka",
        duration: "6–12 months",
        cost: 55000,
        costBreakdown: { tuition: 30000, living: 0, materials: 10000, exams: 15000 },
        outcomes: ["Globally recognised certs", "Vendor-neutral", "High job demand"],
        skillsGained: ["Ethical Hacking", "Incident Response", "Cryptography", "SIEM"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Self-Learning Path",
        type: "TryHackMe + Cybrary + CTF",
        institution: "Online (Freemium)",
        duration: "6–9 months",
        cost: 12000,
        costBreakdown: { tuition: 8000, living: 0, materials: 2000, exams: 2000 },
        outcomes: ["Hands-on hacking labs", "CTF competitions", "Community driven"],
        skillsGained: ["Linux", "Ethical Hacking", "Web App Security", "Network Analysis"],
        badge: "Hands-On",
        badgeColor: "bg-red-100 text-red-700",
        highlight: false,
      },
    ],
  },
  "web-developer": {
    title: "Web Developer",
    description: "Build and maintain websites and web applications, from front-end interfaces to back-end server logic.",
    requiredSkills: ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST APIs", "Git", "Responsive Design"],
    avgStartingSalary: 70000,
    traditional: {
      label: "University Degree",
      type: "BSc IT / Computer Science",
      institution: "SLIIT / UoM / NSBM",
      duration: "3–4 years",
      cost: 1150000,
      costBreakdown: { tuition: 780000, living: 260000, materials: 60000, exams: 50000 },
      outcomes: ["Full academic foundation", "Networking opportunities", "Recognised qualification"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Web Development",
        institution: "IJSE / ESOFT",
        duration: "1 year",
        cost: 130000,
        costBreakdown: { tuition: 90000, living: 25000, materials: 10000, exams: 5000 },
        outcomes: ["Full stack projects", "Industry mentors", "Portfolio-ready"],
        skillsGained: ["HTML/CSS", "JavaScript", "React", "Node.js"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Free Online Path",
        type: "freeCodeCamp + Full Stack Open",
        institution: "Online (Free)",
        duration: "6–9 months",
        cost: 5000,
        costBreakdown: { tuition: 0, living: 0, materials: 3000, exams: 2000 },
        outcomes: ["Completely free", "600+ hours of content", "Certification included"],
        skillsGained: ["HTML/CSS/JS", "React", "Node.js", "APIs"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Certification Path",
        type: "Meta Front-End Developer",
        institution: "Coursera (Online)",
        duration: "7 months",
        cost: 22000,
        costBreakdown: { tuition: 18000, living: 0, materials: 3000, exams: 1000 },
        outcomes: ["Meta-backed certificate", "9 courses", "Capstone project"],
        skillsGained: ["React", "JavaScript", "UI Design", "APIs"],
        badge: "Recognized",
        badgeColor: "bg-orange-100 text-orange-700",
        highlight: false,
      },
    ],
  },
  "network-technician": {
    title: "Network Technician",
    description: "Install, configure and maintain computer networks, ensuring connectivity and performance across organisations.",
    requiredSkills: ["TCP/IP", "Routing", "Switching", "Firewalls", "VPN", "Troubleshooting", "Hardware", "Network Config"],
    avgStartingSalary: 55000,
    traditional: {
      label: "University Degree",
      type: "BSc IT / Network Engineering",
      institution: "SLIIT / UoM",
      duration: "3–4 years",
      cost: 1100000,
      costBreakdown: { tuition: 750000, living: 260000, materials: 50000, exams: 40000 },
      outcomes: ["Engineering foundation", "Academic recognition", "Career versatility"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Networking",
        institution: "NIBM / ACBT",
        duration: "1 year",
        cost: 110000,
        costBreakdown: { tuition: 75000, living: 20000, materials: 10000, exams: 5000 },
        outcomes: ["Lab-based training", "Routing & switching", "Job-ready"],
        skillsGained: ["TCP/IP", "Routing", "Switching", "Firewalls"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "CCNA / CompTIA Network+",
        institution: "ACBT / Cisco NetAcad (Online)",
        duration: "6–9 months",
        cost: 45000,
        costBreakdown: { tuition: 25000, living: 0, materials: 8000, exams: 12000 },
        outcomes: ["Industry gold standard", "Globally recognised", "High employer demand"],
        skillsGained: ["CCNA Routing", "VPN", "Network Security", "Troubleshooting"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
    ],
  },
  "mobile-developer": {
    title: "Mobile App Developer",
    description: "Design and build mobile applications for iOS and Android platforms using modern frameworks.",
    requiredSkills: ["Java/Kotlin", "Swift", "Flutter", "React Native", "APIs", "Mobile UI Design", "App Store Deployment"],
    avgStartingSalary: 80000,
    traditional: {
      label: "University Degree",
      type: "BSc Computer Science / IT",
      institution: "SLIIT / UoM",
      duration: "3–4 years",
      cost: 1200000,
      costBreakdown: { tuition: 800000, living: 280000, materials: 60000, exams: 60000 },
      outcomes: ["Strong fundamentals", "Academic credential", "Research-ready"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Mobile App Development",
        institution: "ESOFT / IJSE",
        duration: "1 year",
        cost: 160000,
        costBreakdown: { tuition: 110000, living: 30000, materials: 12000, exams: 8000 },
        outcomes: ["Android & iOS skills", "Portfolio apps", "Instructor mentored"],
        skillsGained: ["Flutter", "Kotlin", "APIs", "App Store Publishing"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "Meta Android Developer + Flutter",
        institution: "Coursera / Android Developers (Online)",
        duration: "8 months",
        cost: 28000,
        costBreakdown: { tuition: 20000, living: 0, materials: 5000, exams: 3000 },
        outcomes: ["Meta-backed cert", "Cross-platform skills", "Publishable app"],
        skillsGained: ["Kotlin", "Flutter", "Firebase", "UI/UX for Mobile"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
    ],
  },
  "database-administrator": {
    title: "Database Administrator",
    description: "Manage and optimise database systems to ensure data integrity, security, performance and availability.",
    requiredSkills: ["SQL", "Database Design", "Performance Tuning", "Backup & Recovery", "NoSQL", "Cloud Databases"],
    avgStartingSalary: 80000,
    traditional: {
      label: "University Degree",
      type: "BSc IT / Computer Science",
      institution: "UoM / SLIIT",
      duration: "3–4 years",
      cost: 1150000,
      costBreakdown: { tuition: 780000, living: 260000, materials: 60000, exams: 50000 },
      outcomes: ["Deep CS foundation", "Academic recognition", "Enterprise-ready"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Database Management",
        institution: "NIBM / ESOFT",
        duration: "1 year",
        cost: 100000,
        costBreakdown: { tuition: 70000, living: 18000, materials: 8000, exams: 4000 },
        outcomes: ["SQL & NoSQL", "DBA tools", "Real projects"],
        skillsGained: ["SQL", "Oracle", "MySQL", "Indexing"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "Oracle Certified Associate + AWS",
        institution: "Online / Oracle Academy",
        duration: "6–12 months",
        cost: 40000,
        costBreakdown: { tuition: 20000, living: 0, materials: 8000, exams: 12000 },
        outcomes: ["Oracle globally recognised", "Cloud DB skills", "High job demand"],
        skillsGained: ["Oracle DBA", "AWS RDS", "Performance Tuning", "Security"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
    ],
  },
  "project-manager": {
    title: "IT Project Manager",
    description: "Lead and coordinate technology projects, ensuring they are delivered on time, within scope and budget.",
    requiredSkills: ["Agile", "Scrum", "Jira", "Risk Management", "Budgeting", "Stakeholder Management", "SDLC"],
    avgStartingSalary: 100000,
    traditional: {
      label: "University Degree",
      type: "BSc IT / Management",
      institution: "SLIIT / CINEC / UoC",
      duration: "3–4 years",
      cost: 1300000,
      costBreakdown: { tuition: 900000, living: 280000, materials: 70000, exams: 50000 },
      outcomes: ["Management fundamentals", "Academic credential", "Leadership skills"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in IT Project Management",
        institution: "CINEC / SLIIT",
        duration: "1 year",
        cost: 170000,
        costBreakdown: { tuition: 120000, living: 30000, materials: 12000, exams: 8000 },
        outcomes: ["PM methodologies", "Agile & Scrum", "Industry mentors"],
        skillsGained: ["Agile", "Scrum", "Jira", "Risk Management"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "Google PM Certificate + Scrum Master",
        institution: "Coursera / Scrum.org (Online)",
        duration: "6–9 months",
        cost: 30000,
        costBreakdown: { tuition: 22000, living: 0, materials: 5000, exams: 3000 },
        outcomes: ["Globally recognised", "Agile-focused", "Portfolio projects"],
        skillsGained: ["Agile", "Scrum", "Stakeholder Mgmt", "Budgeting"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
      {
        label: "Executive Short Course",
        type: "PMP Prep / PRINCE2 Foundation",
        institution: "ACBT / Online",
        duration: "3 months",
        cost: 60000,
        costBreakdown: { tuition: 45000, living: 0, materials: 8000, exams: 7000 },
        outcomes: ["PMP/PRINCE2 credentials", "Quick upskill", "High employer value"],
        skillsGained: ["PMBOK", "PRINCE2", "MS Project", "Risk Management"],
        badge: "Executive",
        badgeColor: "bg-indigo-100 text-indigo-700",
        highlight: false,
      },
    ],
  },
  "qa-engineer": {
    title: "QA Engineer",
    description: "Ensure software quality through systematic testing, automation, and quality assurance methodologies.",
    requiredSkills: ["Manual Testing", "Test Automation", "Selenium", "Postman", "Bug Tracking", "JIRA", "API Testing"],
    avgStartingSalary: 65000,
    traditional: {
      label: "University Degree",
      type: "BSc IT / Software Engineering",
      institution: "SLIIT / UoM",
      duration: "3–4 years",
      cost: 1150000,
      costBreakdown: { tuition: 780000, living: 260000, materials: 60000, exams: 50000 },
      outcomes: ["Software lifecycle knowledge", "Academic credential", "Broad IT foundation"],
      badge: "Traditional",
      badgeColor: "bg-blue-100 text-blue-700",
    },
    alternatives: [
      {
        label: "Professional Diploma",
        type: "Diploma in Software Testing",
        institution: "ESOFT / IJSE",
        duration: "1 year",
        cost: 120000,
        costBreakdown: { tuition: 80000, living: 24000, materials: 10000, exams: 6000 },
        outcomes: ["Manual & automation", "Real bug tracking", "Job-ready"],
        skillsGained: ["Manual Testing", "Selenium", "JIRA", "Test Planning"],
        badge: "Affordable",
        badgeColor: "bg-green-100 text-green-700",
        highlight: false,
      },
      {
        label: "Certification Path",
        type: "ISTQB Foundation + Selenium",
        institution: "Online / ACBT",
        duration: "4–6 months",
        cost: 25000,
        costBreakdown: { tuition: 14000, living: 0, materials: 5000, exams: 6000 },
        outcomes: ["ISTQB globally recognised", "Automation skills", "Immediate job entry"],
        skillsGained: ["ISTQB", "Selenium", "Postman", "API Testing"],
        badge: "Best Value",
        badgeColor: "bg-purple-100 text-purple-700",
        highlight: true,
      },
    ],
  },
};